#ifndef RASTERIZER_SIZE_GLSL
#define RASTERIZER_SIZE_GLSL

#define SH_DEGREE 3
#define SH_SIZE ((SH_DEGREE + 1) * (SH_DEGREE + 1))

#define T_MIN 0.0001

#define ALPHA_MIN (1.0 / 255.0)
#define ALPHA_MAX 0.99
#define ALPHA_LOG_INV_MIN 5.541263545158426 // log(255)

#define FORWARD_VIEW_DIM 64
#define FORWARD_COPY_DIM_X 8
#define FORWARD_COPY_DIM_Y 8

#define BACKWARD_RESET_DIM 256
#define BACKWARD_RESET_GROUP_COUNT 256
#define BACKWARD_RESET_THREAD_COUNT (BACKWARD_RESET_DIM * BACKWARD_RESET_GROUP_COUNT)
#define BACKWARD_VIEW_DIM 64
#define BACKWARD_COPY_DIM_X 8
#define BACKWARD_COPY_DIM_Y 8

#define SORT_COUNT_BUFFER_OFFSET 4

#define SBUF_MEANS_BINDING 0
#define SBUF_SCALES_BINDING 1
#define SBUF_ROTATES_BINDING 2
#define SBUF_OPACITIES_BINDING 3
#define SBUF_SHS_BINDING 4

#define SBUF_SORT_KEYS_BINDING 5
#define SBUF_SORT_PAYLOADS_BINDING 6
#define SBUF_SORT_SPLAT_INDICES_BINDING 7

#define SBUF_COLORS_MEAN2DXS_BINDING 8
#define SBUF_CONICS_MEAN2DYS_BINDING 9
#define SBUF_VIEW_OPACITIES_BINDING 10

#define SBUF_QUADS_BINDING 11

#define SBUF_DRAW_ARGS_BINDING 12
#define UBUF_SORT_COUNT_BINDING 13

#define SBUF_DISPATCH_ARGS_BINDING 14

#define SIMG_IMAGE0_BINDING 15
#define SIMG_IMAGE1_BINDING 16
#define TEX_IMAGE0_BINDING 17
#define SBUF_PIXELS_BINDING 18
#define IATT_IMAGE0_BINDING 19 // Input Attachment

#define SBUF_DL_DMEANS_BINDING 20
#define SBUF_DL_DSCALES_BINDING 21
#define SBUF_DL_DROTATES_BINDING 22
#define SBUF_DL_DOPACITIES_BINDING 23
#define SBUF_DL_DSHS_BINDING 24

#define SBUF_DL_DCOLORS_MEAN2DXS_BINDING 25
#define SBUF_DL_DCONICS_MEAN2DYS_BINDING 26
#define SBUF_DL_DVIEW_OPACITIES_BINDING 27

#endif
