#ifndef RASTERIZER_SIZE_GLSL
#define RASTERIZER_SIZE_GLSL

#define FORMAT_FLOAT32 0
#define FORMAT_FLOAT16 1
#define FORMAT_UNORM16 2
#define FORMAT_UNORM8 3

#define PIXEL_T_FORMAT FORMAT_FLOAT16

#if PIXEL_T_FORMAT == FORMAT_FLOAT32
#define PIXEL_T_FORMAT_IDENTIFIER rgba32f
#elif PIXEL_T_FORMAT == FORMAT_FLOAT16
#define PIXEL_T_FORMAT_IDENTIFIER rgba16f
#elif PIXEL_T_FORMAT == FORMAT_UNORM16
#define PIXEL_T_FORMAT_IDENTIFIER rgba16
#elif PIXEL_T_FORMAT == FORMAT_UNORM8
#define PIXEL_T_FORMAT_IDENTIFIER rgba8
#else
#error Invalid Format for PIXEL_T Image
#endif

#define DL_DPIXEL_FORMAT FORMAT_FLOAT32

#if DL_DPIXEL_FORMAT == FORMAT_FLOAT32
#define DL_DPIXEL_FORMAT_IDENTIFIER rgba32f
#elif DL_DPIXEL_FORMAT == FORMAT_FLOAT16
#define DL_DPIXEL_FORMAT_IDENTIFIER rgba16f
#else
#error Invalid Format for DL_DPIXEL Image
#endif

#define SH_DEGREE 3
#define SH_SIZE ((SH_DEGREE + 1) * (SH_DEGREE + 1))

#define T_MIN 0.0001

#define ALPHA_MIN (1.0 / 255.0)
#define ALPHA_MAX 0.99
#define ALPHA_LOG_INV_MIN 5.541263545158426 // log(255)

#define FORWARD_VIEW_DIM 64
#define FORWARD_COPY_DIM_X 8
#define FORWARD_COPY_DIM_Y 8

#define BACKWARD_RESET_DIM 256
#define BACKWARD_RESET_GROUP_COUNT 256
#define BACKWARD_RESET_THREAD_COUNT (BACKWARD_RESET_DIM * BACKWARD_RESET_GROUP_COUNT)
#define BACKWARD_VIEW_DIM 64
#define BACKWARD_COPY_DIM_X 8
#define BACKWARD_COPY_DIM_Y 8

#define SORT_COUNT_BUFFER_OFFSET 4

#define SBUF_MEANS_BINDING 0
#define SBUF_SCALES_BINDING 1
#define SBUF_ROTATES_BINDING 2
#define SBUF_OPACITIES_BINDING 3
#define SBUF_SHS_BINDING 4

#define SBUF_SORT_KEYS_BINDING 5
#define SBUF_SORT_PAYLOADS_BINDING 6
#define SBUF_SORT_SPLAT_INDICES_BINDING 7

#define SBUF_COLORS_MEAN2DXS_BINDING 8
#define SBUF_CONICS_MEAN2DYS_BINDING 9
#define SBUF_VIEW_OPACITIES_BINDING 10

#define SBUF_QUADS_BINDING 11

#define SBUF_DRAW_ARGS_BINDING 12
#define UBUF_SORT_COUNT_BINDING 13

#define SBUF_DISPATCH_ARGS_BINDING 14

#define SIMG_PIXELS_TS_BINDING 15
#define SIMG_DL_DPIXELS_BINDING 16
#define TEX_PIXELS_TS_BINDING 17
#define SBUF_PIXELS_BINDING 18
#define IATT_DL_DPIXELS_BINDING 19 // Input Attachment

#define SBUF_DL_DMEANS_BINDING 20
#define SBUF_DL_DSCALES_BINDING 21
#define SBUF_DL_DROTATES_BINDING 22
#define SBUF_DL_DOPACITIES_BINDING 23
#define SBUF_DL_DSHS_BINDING 24

#define SBUF_DL_DCOLORS_MEAN2DXS_BINDING 25
#define SBUF_DL_DCONICS_MEAN2DYS_BINDING 26
#define SBUF_DL_DVIEW_OPACITIES_BINDING 27

#endif
