#ifndef RASTERIZER_SIZE_GLSL
#define RASTERIZER_SIZE_GLSL

#define SH_DEGREE 3
#define SH_SIZE ((SH_DEGREE + 1) * (SH_DEGREE + 1))

#define ALPHA_MIN (1.0 / 255.0)
#define ALPHA_MAX 0.99
#define ALPHA_LOG_INV_MIN 5.541263545158426 // log(255)

#define FORWARD_VIEW_DIM 64
#define BACKWARD_VIEW_DIM 64
#define FORWARD_COPY_DIM_X 8
#define FORWARD_COPY_DIM_Y 8

#define SBUF_MEANS_BINDING 0
#define SBUF_SCALES_BINDING 1
#define SBUF_ROTATES_BINDING 2
#define SBUF_OPACITIES_BINDING 3
#define SBUF_SHS_BINDING 4

#define SBUF_SORT_KEYS_BINDING 5
#define SBUF_SORT_PAYLOADS_BINDING 6
#define SBUF_COLORS_MEAN2DXS_BINDING 7
#define SBUF_CONICS_MEAN2DYS_BINDING 8
#define SBUF_QUADS_BINDING 9
#define SBUF_DRAW_ARGS_BINDING 10
#define UBUF_SORT_COUNT_BINDING 11

#define SORT_COUNT_BUFFER_OFFSET 4

#define SIMG_IMAGE0_BINDING 12
#define TEX_IMAGE0_BINDING 13
#define SBUF_PIXELS_BINDING 14

#endif
