#ifndef DEVICE_SORTER_SIZE_GLSL
#define DEVICE_SORTER_SIZE_GLSL

#define PASS_COUNT 4
#define BITS_PER_PASS 8
#define RADIX (1 << BITS_PER_PASS)

#define KEY_COUNT_BUFFER_OFFSET (2 * 4)

// Global Histogram
#define GLOBAL_HIST_DIM 128
#define GLOBAL_HIST_PART_SIZE (GLOBAL_HIST_DIM * RADIX)

// OneSweep Sort
#define SORT_DIM RADIX
#define SORT_KEYS_PER_THREAD 15
#define SORT_PART_SIZE (SORT_DIM * SORT_KEYS_PER_THREAD)

// Bindings
#define B_KEY_COUNT_BINDING 0
#define B_INDIRECT_ARGS_BINDING 1
#define B_GLOBAL_HISTS_BINDING 2
#define B_PASS_HISTS_BINDING 3
#define B_INDICES_BINDING 4
#define B_SRC_KEYS_BINDING 5
#define B_SRC_PAYLOADS_BINDING 6
#define B_DST_KEYS_BINDING 7
#define B_DST_PAYLOADS_BINDING 8

#endif
