#ifndef DEVICE_SORTER_SIZE_GLSL
#define DEVICE_SORTER_SIZE_GLSL

#define PASS_COUNT 4
#define BITS_PER_PASS 8
#define RADIX (1 << BITS_PER_PASS)

#define KEY_COUNT_BUFFER_OFFSET (1 * 4)

// Reset
#define RESET_DIM 256
#define RESET_GROUP_COUNT 256

// Global Histogram
#define GLOBAL_HIST_DIM RADIX
#define GLOBAL_HIST_KEYS_PER_THREAD 45
#define GLOBAL_HIST_PART_SIZE (GLOBAL_HIST_DIM * GLOBAL_HIST_KEYS_PER_THREAD)

// OneSweep Sort
#define SORT_DIM RADIX
#define SORT_KEYS_PER_THREAD 15
#define SORT_PART_SIZE (SORT_DIM * SORT_KEYS_PER_THREAD)

// Bindings
#define UBUF_KEY_COUNT_BINDING 0
#define SBUF_DISPATCH_ARGS_BINDING 1
#define SBUF_GLOBAL_HISTS_BINDING 2
#define SBUF_PASS_HISTS_BINDING 3
#define SBUF_INDICES_BINDING 4
#define SBUF_SRC_KEYS_BINDING 5
#define SBUF_SRC_PAYLOADS_BINDING 6
#define SBUF_DST_KEYS_BINDING 7
#define SBUF_DST_PAYLOADS_BINDING 8

#endif
